zuul:
  #All service could take cookie
  sensitive-headers: 
  routes:
    #/myProduct/product/list -> /product/product/list
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
    ##or anther Method:serviceId:path
    #product: /myProduct/**
    # type is set
  ignored-patterns:
    #- /**/product/list
management:
  security:
    enabled: false
spring:
  redis:
    host: 106.14.3.142
    port: 6379
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

