spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.65.130/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 106.14.3.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: 106.14.3.142
    port: 6379
  jpa:
    show-sql: true
env:
  test1
